version: "3.12"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
        - "8000:8000"
    volumes:
      - .:/prod
      - /prod/.venv
    command: uvicorn wsgi:app --host 0.0.0.0